YourWebsite/YourWebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from mainapp import views

urlpatterns = [
    path('', include('authapp.urls', namespace='authapp')),
    path('', views.main, name='main'),
    path('admin/', admin.site.urls),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

YourWebsite/authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'auth'

urlpatterns = [
    path("login/", authapp.login, name="login"),
    path("logout/", authapp.logout, name="logout"),
    path("register/", authapp.register, name="register"),
    path("edit/", authapp.edit, name="edit"),
]

YourWebsite/authapp/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    city = models.CharField(max_length=64, verbose_name="Город", blank=True)
    phone_number = models.CharField(max_length=14, verbose_name="Телефон", blank=True)

YourWebsite/mainapp/models.py
from django.db import models

# Create your models here.

YourWebsite/authapp/forms.py
from django import forms
from django.contrib.auth.forms import (
    AuthenticationForm,
    UserChangeForm,
    UserCreationForm,
)

from .models import User

class UserLoginForm(AuthenticationForm):
    class Meta:
        fields = ("username", "password")

    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"


class UserEditForm(UserChangeForm):
    class Meta:
        fields = (
            "username",
            "first_name",
            "email",
            "password",
            "phone_number",
        )

        model = User

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"
            field.help_text = ""
            if field_name == "password":
                field.widget = forms.HiddenInput()


class UserRegisterForm(UserCreationForm):
    class Meta:
        fields = (
            "username",
            "first_name",
            "password1",
            "password2",
            "email",
        )
        model = User

    def __init__(self, *args, **kwargs):
        super(UserRegisterForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"
            field.help_text = ""

YourWebsite/authapp/views.py
from django.contrib import auth
from django.shortcuts import HttpResponseRedirect, render
from django.urls import reverse

from authapp.forms import UserEditForm, UserLoginForm, UserRegisterForm

def login(request):
    title = "Login"

    login_form = UserLoginForm(data=request.POST)
    if request.method == "POST" and login_form.is_valid():
        username = request.POST["username"]
        password = request.POST["password"]

        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            return HttpResponseRedirect(reverse("main"))

    return render(
        request,
        "authapp/login.html",
        context={
            "title": title,
            "login_form": login_form,
        },
    )


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse("main"))


def register(request):
    title = "Register"

    if request.method == "POST":
        register_form = UserRegisterForm(request.POST)

        if register_form.is_valid():
            register_form.save()
            return HttpResponseRedirect(reverse("auth:login"))
    else:
        register_form = UserRegisterForm()

    return render(
        request,
        "authapp/register.html",
        context={
            "title": title,
            "register_form": register_form,
        },
    )


def edit(request):
    title = "Editing"

    if request.method == "POST":
        edit_form = UserEditForm(request.POST, request.FILES, instance=request.user)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse("auth:edit"))
    else:
        edit_form = UserEditForm(instance=request.user)

    return render(
        request,
        "authapp/edit.html",
        context={
            "title": title,
            "edit_form": edit_form,
        },
    )

YourWebsite/mainapp/views.py
from django.shortcuts import render


def main(request):
    menu_links = [
        {"href": "mainapp:main", "name": "Design"},
        {"href": "mainapp:main", "name": "Collaborate"},
        {"href": "mainapp:main", "name": "Apps"},
        {"href": "mainapp:main", "name": "Resources"},
        {"href": "mainapp:main", "name": "Pricing"},
    ]

    title = 'Your Website'

    content = {
        'title': title,
        'menu_links': menu_links,
    }
    return render(request, 'mainapp/main.html', content)

YourWebsite/authapp/templates/authapp/base.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
        {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}

    {% endblock %}
</head>

<body>
    <div class="container">
        <div class="login" style="display: flex;
        flex-direction: column;
        align-items: center;">

            {% block content %}

            {% endblock %}
        </div>
    </div>
</body>

</html>

YourWebsite/authapp/templates/authapp/edit.html
{% extends 'authapp/base.html' %}
{% load static %}


{% block content %}
    <div class="h2 text-center head">
        Editing
    </div>    
    <form class="form-horizontal" action="{% url 'auth:edit' %}" method="post" enctype="multipart/form-data" style="text-align: center; ">
        {% csrf_token %}
        {{ edit_form.as_p }}
        <input class="form-control" type="submit" value="Save">
    </form>
    <button class="btn btn-round form-control last">
        <a href="{% url 'main' %}" class="">
            на главную
        </a>
    </button>
{% endblock %}

YourWebsite/authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load static %}
{% block content %}
    <div class="h2 text-center head">
        authentication
    </div>    
    <form class="form-horizontal" action="{% url 'auth:login' %}" method="post" style="text-align: center; ">
        {% csrf_token %}
        {{ login_form.as_p }}
        <br>
        <input class="form-control" type="submit" value="Login">
    </form>
    <a href="{% url 'main' %}" class="btn_on_main"> 
        Main page
    </a>
{% endblock %}

YourWebsite/authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}
    <div class="h2 text-center head">
        Registration
    </div>    
    <form class="form-horizontal" action="{% url 'auth:register' %}" method="post" enctype="multipart/form-data" style="text-align: center; ">
        {% csrf_token %}
        {{ register_form.as_p }}
        <br>
        <input class="form-control" type="submit" value="Registration">
    </form>
    <a href="{% url 'main' %}" class="btn_on_main"> 
        Main page
    </a>
{% endblock %}

YourWebsite/mainapp/templates/mainapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href={% static 'main.css' %}>
    <title>
        {% block 'title' %}
            {{ title|title }}
        {% endblock 'title' %}
    </title>
</head>

<body>
    {% block 'content' %}
    {% endblock 'content' %}
</body> 

</html>

YourWebsite/mainapp/templates/mainapp/include/inc__footer__menu.html
<footer class="footer">
    <div class="container">
        <div class="footer__top">
            <div class="footer__top__info">
                <p class="footer__top__text">
                    Subscribe to our newsletter
                </p>
                <p class="footer__top__text">
                    A monthly digest of the latest Sketch news, articles, and resources.
                </p>
            </div>
            <form>
                <div class="mb-3">
                    <input type="email"
                           class="form-control email"
                           placeholder="Email"
                           id="exampleInputEmail1"
                           aria-describedby="emailHelp">
                </div>
                <div class="mb-3 form-check">
                    <input type="checkbox" class="form-check-input" id="exampleCheck1">
                    <label class="form-check-label" for="exampleCheck1">
                        I agree to receive marketing emails from
                        Sketch.
                    </label>
                </div>
                <button type="submit" class="btn btn-primary ">Submit</button>
            </form>
        </div>
        <hr class="hr">
        <div class="footer__bot">
            <ul class="footer__list">
                <li class="footer__item">
                    <a href="" class="black">Sketch</a>
                </li>
                <li class="footer__item">
                    <a href="" class="footer__link">Overview</a>
                </li>
                <li class="footer__item">
                    <a href="" class="footer__link">Design</a>
                </li>
                <li class="footer__item">
                    <a href="" class="footer__link">Collaborate</a>
                </li>
                <li class="footer__item">
                    <a href="" class="footer__link">Pricing</a>
                </li>
            </ul>
            <ul class="footer__list">
                <li class="footer__item">
                    <a href="" class="black">Sketch</a>
                </li>
                <li class="footer__item">
                    <a href="" class="footer__link">Overview</a>
                </li>
                <li class="footer__item">
                    <a href="" class="footer__link">Design</a>
                </li>
                <li class="footer__item">
                    <a href="" class="footer__link">Collaborate</a>
                </li>
                <li class="footer__item">
                    <a href="" class="footer__link">Pricing</a>
                </li>
            </ul>
            <ul class="footer__list">
                <li class="footer__item">
                    <a href="" class="black">Sketch</a>
                </li>
                <li class="footer__item">
                    <a href="" class="footer__link">Overview</a>
                </li>
                <li class="footer__item">
                    <a href="" class="footer__link">Design</a>
                </li>
                <li class="footer__item">
                    <a href="" class="footer__link">Collaborate</a>
                </li>
                <li class="footer__item">
                    <a href="" class="footer__link">Pricing</a>
                </li>
            </ul>
            <ul class="footer__list">
                <li class="footer__item">
                    <a href="" class="black">Sketch</a>
                </li>
                <li class="footer__item">
                    <a href="" class="footer__link">Overview</a>
                </li>
                <li class="footer__item">
                    <a href="" class="footer__link">Design</a>
                </li>
                <li class="footer__item">
                    <a href="" class="footer__link">Collaborate</a>
                </li>
                <li class="footer__item">
                    <a href="" class="footer__link">Pricing</a>
                </li>
            </ul>
            <ul class="footer__list">
                <li class="footer__item">
                    <a href="" class="black">Sketch</a>
                </li>
                <li class="footer__item">
                    <a href="" class="footer__link">Overview</a>
                </li>
                <li class="footer__item">
                    <a href="" class="footer__link">Design</a>
                </li>
                <li class="footer__item">
                    <a href="" class="footer__link">Collaborate</a>
                </li>
                <li class="footer__item">
                    <a href="" class="footer__link">Pricing</a>
                </li>
            </ul>
        </div>
        <div class="footer__info">
            <p class="footer__col">
                © 2021 Sketch B.V.
            </p>
        </div>
    </div>
</footer>